- name: Refresh packages
  apt:
    update_cache: true
- name: Install aptitude
  apt:
    name: aptitude
    state: present
- name: Install ag
  apt:
    name: silversearcher-ag
    state: present
- name: Create code directory
  ansible.builtin.file:
    path: /home/ubuntu/code
    state: directory
