- hosts: all
  become: yes
  roles:
  - common
  - role: gantsign.oh-my-zsh
    users:
      - username: ubuntu

- hosts: dot-net-dev
  become: yes
  roles:
  - dot-net-dev

- hosts: node-dev
  become: yes
  roles:
  - node-dev
