- hosts: dot-net-dev
  become: yes
  roles:
  - dot-net-dev

- hosts: node-dev
  become: yes
  roles:
  - andrelohmann.nodesource
  - node-dev
  vars:
  - host_username: ubuntu
  - nodesource_nodejs_version: '14'

- hosts: cypress-dev
  become: yes
  tasks:
  - name: Install packages cypress requires
    apt:
      name:
      - libgtk2.0-0
      - libgtk-3-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
      - libxtst6
      - xauth
      - xvfb
