- hosts: all
  become: yes
  roles:
  - common
  - role: gantsign.oh-my-zsh
    users:
      - username: "{{ host_username }}"
  vars:
  - host_username: ubuntu

- hosts: dot-net-dev
  become: yes
  roles:
  - dot-net-dev

- hosts: node-dev
  become: yes
  roles:
  - node-dev
  vars:
  - host_username: ubuntu

- hosts: cypress-dev
  become: yes
  tasks:
  - name: Install packages cypress requires
    apt:
      name:
      - libgtk2.0-0
      - libgtk-3-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
      - libxtst6
      - xauth
      - xvfb
