- hosts: docker-dev
  vars:
  - host_username: ubuntu
  become: yes
  tasks:
  - name: Install Docker pre-requisites
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Add Ondrej PHP Repository
    apt_repository:
      repo: ppa:ondrej/php
      update_cache: true
  - name: Add PHP 8
    apt:
      name:
      - php8.0
      - php8.0-xml
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  - name: Refresh packages
    apt:
      update_cache: true
  - name: Install Docker Engine
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
  - name: Add user to docker group
    user:
      name: "{{ host_username }}"
      append: yes
      groups:
      - docker
